stages: 
  - test
  - build 
  - upload
  - publish
  
before_script:
  - git submodule sync
  - git submodule update --init --recursive
#Tests
basetest-linux-i386:
  stage: test 
  script: 
    - lazbuild promet/source/testcases/consoletest.lpi
    - promet/output/i386-linux/consoletest --mandant=help --config-path=./promet/help/config
  tags:
    - linux-i386
webdavtest-linux-i386:
  stage: test 
  script: 
    - lazbuild promet/source/testcases/consoletest_webdav.lpi
    - promet/output/i386-linux/consoletest_webdav --mandant=help --config-path=./promet/help/config
  tags:
    - linux-i386
#Build
build-windows:
  stage: build 
  script: git-bash build.sh all
  tags:
    - windows-i386
  only:
    - master
  cache:
    paths:
      - promet/setup/output
upload-windows:
  stage: upload
  script: git-bash build.sh upload
  dependencies:
    - build-windows
  tags:
    - windows-i386
  cache:
    paths:
      - promet/setup/output
publish-windows:
  stage: publish
  script: git-bash promet/setup/i386-win32/change_wiki_windows.sh
  dependencies:
    - upload-windows
  tags:
    - windows-i386
  only:
    - tags
  cache:
    paths:
      - promet/setup/output

build:linux:i386:
  stage: build 
  script: bash build.sh all
  tags:
    - linux-i386
  only:
    - master
  cache:
    paths:
      - promet/setup/output

upload:linux:i386:
  stage: upload
  script: bash build.sh upload
  dependencies:
    - build:linux:i386
  tags:
    - linux-i386
  cache:
    paths:
      - promet/setup/output

build:linux:x86-64:
  stage: build 
  script: bash build.sh all
  tags:
    - linux-x64
  only:
    - master
  cache:
    paths:
      - promet/setup/output

upload:linux:x86-64:
  stage: upload
  script: bash build.sh upload
  dependencies:
  - build:linux:i386
  tags:
    - linux-x64

build:linux:arm:
  stage: build 
  script:
    - git clean -fdx
    - git submodule foreach git reset --hard
    - bash build.sh server
  tags:
    - linux-arm
  only:
    - master
  cache:
    paths:
      - promet/setup/output

upload:linux:arm:
  stage: upload
  script: bash build.sh upload
  dependencies:
  - build:linux:arm
  tags:
    - linux-arm
    
cleanup_build_job:
  stage: build
  script:
  - rm -R promet
  - rm -R general
when: on_failure