before_script:
  - git submodule update --init --recursive
build:
  script:
    - bash build.sh all
    
build-windows:
  script: git-bash build.sh all
  tags:
    - windows-i386
build-linux-i386:
  script: bash build.sh all
  tags:
    - linux-i386
