stages: 
  - test
  - build 
  - publish
  
before_script:
  - git submodule sync
  - git submodule update --init --recursive

basetest-linux-i386:
  stage: test 
  script: 
    - lazbuild promet/source/testcases/consoletest.lpi
    - promet/output/i386-linux/consoletest --mandant=help --config-path=./promet/help/config
  tags:
    - linux-i386
webdavtest-linux-i386:
  stage: test 
  script: 
    - lazbuild promet/source/testcases/consoletest_webdav.lpi
    - promet/output/i386-linux/consoletest_webdav --mandant=help --config-path=./promet/help/config
  tags:
    - linux-i386

build:windows:
  stage: build 
  script: git-bash build.sh all
  tags:
    - windows-i386
publish:windows:
  stage: deploy
  script: git-bash build.sh upload
  dependencies:
  - build:windows

build:linux:i386:
  stage: build 
  script: bash build.sh all
  tags:
    - linux-i386
    
publish:linux:i386:
  stage: publish
  script: bash build.sh upload
  dependencies:
  - build:linux:i386
  tags:
    - linux-i386
  
build:linux:x86-64:
  stage: build 
  script: bash build.sh all
  tags:
    - linux-x64

publish:linux:x86-64:
  stage: publish
  script: bash build.sh upload
  dependencies:
  - build:linux:i386
  tags:
    - linux-x64

build:linux:arm:
  stage: build 
  script:
    - git clean -fdx
    - bash build.sh server
  tags:
    - linux-arm

publish:linux:arm:
  stage: publish
  script: bash build.sh upload
  dependencies:
  - build:linux:arm
  tags:
    - linux-arm
