stages: 
  - test
  - build 
  - upload
  - publish
  
before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - git clean -fdx
  - git submodule foreach git reset --hard
  
variables:
  GIT_STRATEGY: fetch
  # or clone
  # fetch or clone only the last 3 commits
  GIT_DEPTH: "3"

#Tests
basetest-linux:
  image: build-lazarus-x64:latest
  stage: test 
  script: 
    - apt-get install lazarus sqlite3 libusb-dev libsane-dev zip git -y
    - lazbuild promet/source/testcases/consoletest.lpi
    - promet/output/x86_64-linux/consoletest --mandant=help --config-path=./promet/help/config
  tags:
    - docker-lazarus-x64
webdavtest-linux:
  image: build-lazarus-x64:latest
  stage: test 
  script: 
    - lazbuild promet/source/testcases/consoletest_webdav.lpi
    - promet/output/x86_64-linux/consoletest_webdav --mandant=help --config-path=./promet/help/config
  tags:
    - docker-lazarus-x64
mysql-test:
  image: build-lazarus-x64:latest
  services:
    - mysql:latest
  variables:
    # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
    MYSQL_DATABASE: testdb
    MYSQL_ROOT_PASSWORD: password
  stage: test 
  script:  
    - sudo apt-get install -y mysql-client libmysqlclient-dev
    - lazbuild promet/source/testcases/consoletest.lpi
    - promet/output/x86_64-linux/consoletest --mandant=help --config-path=./promet/help/config
  tags:
    - docker-lazarus-x64
#Build
build:windows:
  stage: build 
  variables:
#    GIT_STRATEGY: clone
  script: 
    - git submodule sync --recursive
    - bash build.sh all
  tags:
    - windows-i386
  only:
    - master
  artifacts:
    paths:
      - promet/setup/output
    expire_in: 1 week  

build:linux:i386:
  stage: build 
  script: 
    - bash build.sh all
  tags:
    - linux-i386
  only:
    - master
  artifacts:
    paths:
      - promet/setup/output
    expire_in: 1 week  

build:linux:x86-64:
#  image: build-lazarus-x64:latest
  stage: build 
  script: 
    - sshpass -p $AUTOUPLOAD_PW ssh-copy-id $AUTOUPLOAD_USER@$AUTOUPLOAD_HOST -p $AUTOUPLOAD_PORT 
    - bash build.sh all
  tags:
    - linux-x64
#    - docker-lazarus-x64
  only:
    - master
  artifacts:
    paths:
      - promet/setup/output
    expire_in: 1 week  

build:linux:arm:
  variables:
    GIT_DEPTH: ""
#    GIT_STRATEGY: clone
  before_script:
    - git submodule sync
    - git submodule foreach git submodule update
    - git submodule update --init --recursive
  stage: build 
  script:
    - git clean -fdx
    - git submodule foreach git reset --hard
    - bash build.sh server
  tags:
    - linux-arm
  only:
    - master
  artifacts:
    paths:
      - promet/setup/output
    expire_in: 1 week  
  allow_failure: true      

upload:all:
  before_script:
    - ls -l promet/setup/output/*
  stage: upload
  script:
    - sshpass -p $AUTOUPLOAD_PW ssh-copy-id $AUTOUPLOAD_USER@$AUTOUPLOAD_HOST -p $AUTOUPLOAD_PORT
    - bash promet/setup/upload_builds.sh
  dependencies:
    - build:linux:arm
    - build:linux:i386
    - build:linux:x86-64
    - build:windows
  artifacts:
    paths:
      - promet/setup/output/act_alphadownload.txt
    expire_in: 1 week
  tags:
    - linux-x64

update:containers:
  before_script:
    - ls -l promet/setup/output/*
  stage: upload
  script:
    - bash promet/setup/build_containers.sh
  tags:
    - docker-x64
  allow_failure: true
